spring.application.name=replan-ai

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=replan_ai

server.port=${PORT:8080}

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=openai/gpt-oss-120b